version: "3.8"

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: inventory_db
      DB_USERNAME: admin
      DB_PASSWORD: adminpassword
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped
    networks:
      - stock-alert-net

  postgres:
    image: postgres:16-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data
    networks:
      - stock-alert-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: inventory-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - stock-alert-net

  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    networks:
      - stock-alert-net

volumes:
  inventory-postgres-data:

networks:
  stock-alert-net:
    driver: bridge
